[tool.poetry]
name = "HA API"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"
fastapi = "^0.70.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"